version: '3'

services: 
    web:
        build: ./web
        ports:
            - "5000:5000"
        volumes:
            - .:/DonutFactoryAPI
            - logvolume01:/var/log
volumes:
    logvolume01: {}
